### PR TITLE
Fix Invalid State Error in IE11

### PR DESCRIPTION
**Pull request by awoodford**
This fixes an issue I came across whilst implimenting Instafeed into a clients website which required IE11 Support >.<

Screen grab of error: https://i.imgur.com/0JGmKdc.png

### CODE REVIEW

**Comment by stevenschobert** [comment]
Hey @awoodford! Thank you so much for PR! This bug was on our todo list too (#651), so great timing!

Do you have any docs you can link me to on why the timeout needs to be set after the `open()` invocation? I'm curious as to why IE has that requirement!

Thanks, we'll get this merged in for the next release (RC2)!

🎉 🎉

**Comment by awoodford** [comment]
Hey @stevenschobert 

No worries! I'm glad it was something that people acually need/want.

This where I found out that the timeout has to be declared after the request is opened: **https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/timeout**

**Comment by stevenschobert** [comment]
> In Internet Explorer, the timeout property may be set only after calling the open() method and before calling the send() method.

Yep, I see it now too! I totally missed that when reading the docs. Thanks -- excellent fix.

**Comment by awoodford** [comment]
Thank you for all your working in creating this plugin as well, its been a life saver!

**Comment by stevenschobert** [comment]
Hey @awoodford -- just letting you know that this fix has been included in [v2.0.0-rc2](https://github.com/stevenschobert/instafeed.js/releases/tag/v2.0.0-rc2)

**Comment by awoodford** [comment]
Hi @stevenschobert,

That's great! Thanks for letting me know :)

**Pull request merged**
