### PR TITLE
Improving userId error message as suggested in Issue #254

### PR DESCRIPTION
**Pull request by ry167**
This also fixes the confusion in Issue #251 

The test has been updated too so that it matches this

### CODE REVIEW

**Comment by ry167** [comment]
The Travis check is due to line length being 96, not <= 80.
I don't know the best way to fix that in Coffeescript

**Comment by stevenschobert** [comment]
Hey @ry167! Thank you for your contribution! I wasn't able to merge these changes directly, but [v1.4](https://github.com/stevenschobert/instafeed.js/releases/tag/v1.4.0) no longer complains about type mismatches in these options.

**Comment by ry167** [comment]
All good, could you also close issue #251 and #254 which are relevant for this, thanks.

**Comment by stevenschobert** [comment]
@ry167 Done! Thanks for pointing those out. My issue backlog is huge, so it was really helpful.

**Pull request closed without merging**
