### PR TITLE
Adds a square-crop option to automatically crop images

### PR DESCRIPTION
**Pull request by benjamin-hull**
This option adds a wrapper element and some basic styling to crop images to a square, regardless of the original orientation. This should work in most simple cases, but there definitely will be some layouts it's not suitable for. It's really designed to handle the common case where users just drop in the script and point it at their username.

The starting point was this discussion: https://github.com/stevenschobert/instafeed.js/issues/527 and the fact that the workarounds no longer work, now that Instagram rejects unsigned URLs.

The new option is off by default, so everything should be backwards-compatible.

Lastly, this is my first foray into CoffeeScript, so let me know if I've got the style wrong or done anything dumb anywhere!

### CODE REVIEW

**Comment by stevenschobert** [comment]
Hey @benjamin-hull! Thank you for the contribution!

I've been super busy with other projects, but I'm really happy you took the time to put up the code here. I took a really brief glance at it, and everything looks good. The documentation additions is super helpful, so thanks for that.

Since it's a new feature, I'll probably end up pulling this into a v1.5 release, rather than v1.4.2, so I'll probably revert that commit (no worries though!).

I'll try to get this into a release as soon as I can, thanks!

**Comment by benjamin-hull** [comment]
No problem, mate. I've probably used your code on a dozen sites now, so it's the least I could do, really. Plus, forced me to look at CoffeeScript finally, too, so that's a bonus.

Makes much more sense as a 1.5 now that I think about it, too.

Thanks again for a great little lib!

**Comment by jackputtock** [comment]
Hello; Steven, Benjamin,
What is the estimate for the release of 1.5? This feature would be awesome on my site as some of my recent Instagram images were not in the same aspect ratio or size as the rest causing it to push / mess up scaling. 

Jack.

**Comment by joeygallegos** [comment]
I am having the same issue and this would help a whole lot. Do we have an ETA on the next major release for instafeed?

**Comment by benjamin-hull** [comment]
Hey @joeygallegos and @jackputtock - sorry for the delay. I know Steven's been up to his eyeballs on other projects, so as far as I know there's no timeline for the next release. Likely it will contain more than just this fix, though.

In the meantime, it's easy enough to achieve this yourself using the `template` options in instafeed.js, plus some simple CSS. I've got an example of that here: https://codepen.io/benjamin-hull/pen/xWprYe

If you have trouble with the CSS, feel free to leave a comment on the CodePen example, that way others can find it, too.

Thanks!

**Pull request closed without merging**
